### PR TITLE
📝 Add note for java.awt.AWTError resolution

### PR DESCRIPTION
**Pull request by pzrq**
Needed for my 18.04.3 LTS VM.

### CODE REVIEW

**Comment by pzrq** [comment]
Full stack trace just in case it proves useful to someone:

```
$ roboviz.sh 
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
	at jogamp.nativewindow.jawt.JAWTJNILibLoader$1.run(JAWTJNILibLoader.java:56)
	at java.security.AccessController.doPrivileged(Native Method)
	at jogamp.nativewindow.jawt.JAWTJNILibLoader.loadAWTImpl(JAWTJNILibLoader.java:51)
	at jogamp.nativewindow.jawt.JAWTUtil.<clinit>(JAWTUtil.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jogamp.common.util.ReflectionUtil.callMethod(ReflectionUtil.java:266)
	at javax.media.nativewindow.NativeWindowFactory.initSingleton(NativeWindowFactory.java:203)
	at javax.media.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1164)
	at javax.media.opengl.GLProfile.access$000(GLProfile.java:71)
	at javax.media.opengl.GLProfile$1.run(GLProfile.java:117)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.media.opengl.GLProfile.initSingleton(GLProfile.java:115)
	at javax.media.opengl.GLProfile.validateInitialization(GLProfile.java:1428)
	at javax.media.opengl.GLProfile.getProfileMap(GLProfile.java:1580)
	at javax.media.opengl.GLProfile.get(GLProfile.java:623)
	at javax.media.opengl.GLProfile.get(GLProfile.java:630)
	at rv.Viewer.main(Viewer.java:442)
```

**Review by tripta96 — APPROVED** [review]

**Comment by jayenashar** [comment]
wouldn't it be better to install the non-headless packages?

**Comment by pzrq** [comment]
> wouldn't it be better to install the non-headless packages?

Honestly, I don't know. What might the pros/cons of that be over this one-line solution?

It took me a good half hour to find because my searches unfortunately kept coming up with please install Java Access Bridge on Windows, which is naturally of no value to rUNSWift on Linux.

**Comment by jayenashar** [comment]
pros: people don't have to follow the link and then install the non-headless packages manually?
cons: not sure what the pros are of adding a manual step

**Comment by pzrq** [comment]
I'm not sure what you're referring to? There was no installation?

**Comment by pzrq** [comment]
Also this suggested manual step of disabling assistive technologies may not be required for all JDKs in Ubuntu/Debian/other Linux environments?

**Comment by jayenashar** [comment]
Clearly I've misunderstood the link and this one-line solution is insufficient.

From the link:
> did not want to install the non-headless version of OpenJDK due to the number of additional dependencies

What I'm proposing is that we remove `-headless` from https://github.com/UNSWComputing/rUNSWift/blob/master/bin/setup-simulation.sh#L26

`setup-simulation.sh` is [all scripts are] specific to debian/ubuntu and I'm quite happy for the modification to keep it that way.

**Comment by pzrq** [comment]
> What I'm proposing is that we remove `-headless` from https://github.com/UNSWComputing/rUNSWift/blob/master/bin/setup-simulation.sh#L26

Thank you, that makes a lot more sense to try out as time permits.

**Pull request merged**
