### PR TITLE
update team photo

### PR DESCRIPTION
**Pull request by abhivij**
suggesting alternate team photo including just the members

### CODE REVIEW

**Comment by pzrq** [comment]
Builds on top of #31

**Review by pzrq — APPROVED** [review]
This as is will orphan a photo but I also think that's ok 👍🏼

**Comment by ijnek** [comment]
Looks good, make sure you delete the .png photo!

**Comment by pzrq** [comment]
> Looks good, make sure you delete the .png photo!

Yeah if it doesn't happen in this PR someone probably will raise another one.

**Comment by pzrq** [comment]
To be clear, just waiting on someone else to merge, so it represents a travelling team majority decision, even if it's not necessarily unanimous.

**Comment by abhivij** [comment]
@pzrq @ijnek removed unused photo

**Review by ijnek — APPROVED** [review]

**Review by pzrq — APPROVED** [review]

**Comment by n33r4j** [comment]
👍

**Review by n33r4j — APPROVED** [review]

**Comment by n33r4j** [comment]
A recruit reported that the photo was not displaying correctly on Safari. Can someone with a Mac check it out ?

**Comment by jayenashar** [comment]
image
it would be better cropped but it seems fine to me

**Comment by pzrq** [comment]
@n33r4j Please ask for a screenshot in future, or better yet, let them know PRs are welcome too!

e.g. Safari could also be iOS (iPhone SE 2 below) or iPadOS (not shown).

I also cannot reproduce anything obviously wrong?

Here's Firefox 110.0 vs Safari 16.3 on an Intel Mac (not sure about M1/M2 though it should be the same MacOS / Safari):
Screenshot 2023-02-22 at 21 40 12

iPhone SE 2 / Safari 16.3:
IMG_9FCD9AFE5B27-1

**Pull request merged**
