### PR TITLE
improve installation instructions by using requirements.txt

### PR DESCRIPTION
**Pull request by ijnek**
Having a requirements.txt is the recommended way to list libraries to be installed. It makes adding more libraries easier as there is no need to modify ``README.md``.

### CODE REVIEW

**Comment by jayenashar** [comment]
i'm confused why we would need to add more libraries.  also you seem to have split the dependencies now between apt and pip, between readme and requirements...

**Comment by ijnek** [comment]
Thanks for reviewing @jayenashar!

Took a bit of time to remember why ``requirements.txt`` is recommended. It's because ReadTheDocs server looks for whether a``requirements.txt`` exists before compiling the docs, and if it does, it installs all dependencies before building.

It's good to reuse this ``requirements.txt`` for a team member building the docs by hand, rather than use the dependencies from apt, to closely match what's being done on the ReadTheDocs server.

> also you seem to have split the dependencies now between apt and pip, between readme and requirements...

Yes.. let me fix that and make everything pip.

**Comment by ijnek** [comment]
I've also added a commonly-used extension that is useful when copying commands (to demonstrate how to add more plugins to requirements.txt):

image

**Comment by pzrq** [comment]
FWIW, 👍🏼 for `pip` and `requirements.txt` as it's how most people in the Python community start to do something, though if anyone can link to how RTD does it that would be the most important one (i.e. use what they use in production).

In practice `apt` is great up the point one needs a [venv](https://docs.python.org/3/library/venv.html) and then it gets messy if one is doing multiple projects with different dependency versions required (unlike the NodeJS community that does `node_modules`, I'm a fan of the NodeJS pattern to solve the [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell) problem) and `requirements.txt` is a natural step towards that.

**Pull request merged**
