### PR TITLE
New native build

### PR DESCRIPTION
**Pull request by jayenashar**
not sure where you saw that relwithdebinfo is for debugging only, but i added native to this list

### CODE REVIEW

**Comment by Isheetas** [comment]
> not sure where you saw that relwithdebinfo is for debugging only, but i added native to this list

Yea wasnt sure reading the GDB Server section

**Comment by jayenashar** [comment]
https://runswift.readthedocs.io/en/latest/debugging/gdb_server.html ?  it's not meant to imply that relwithdebinfo is for debugging only.  if you can suggest a way to reword it, please edit https://github.com/UNSWComputing/rUNSWift-docs/edit/master/source/debugging/gdb_server.rst

**Comment by jayenashar** [comment]
blocked by https://github.com/UNSWComputing/rUNSWift/pull/2385

**Comment by jayenashar** [comment]
> blocked by [UNSWComputing/rUNSWift#2385](https://github.com/UNSWComputing/rUNSWift/pull/2385)

unblocked in september

**Review by EthanJonesUNSW — APPROVED** [review]
Looks good to me. Pehaps add something about tiny-jnn compatibility if we want that here.

**Comment by jayenashar** [comment]
> Looks good to me. Pehaps add something about tiny-jnn compatibility if we want that here.

having a bit of trouble with rst, but added something

**Comment by pzrq** [comment]
LGTM :shipit: 

Sorry it took so long to come back and see this again.

**Pull request merged**
