### PR TITLE
Update team photo

### PR DESCRIPTION
**Pull request by ijnek**
I've been wanting to do this for a while. It makes sense to have the real active warriors on the front page!
Let's store old team photos in a separate page.

### CODE REVIEW

**Comment by jayenashar** [comment]
i think it's ok to show multiple teams on the home page

**Comment by ijnek** [comment]
I think the front page should be kept short and simple with only one photo.

**Review by pzrq — APPROVED** [review]
👍🏼 I like the one photo per year on a new team photos page, though if appropriate I am also happy to wait for another opinion.

@limenutt @abhivij @n33r4j ?

**Comment by n33r4j** [comment]
Perhaps keep the latest photo on top and have the previous teams as a film strip below or in [tabs](https://sphinx-tabs.readthedocs.io/en/latest/) based on the year ?

**Comment by ijnek** [comment]
I don't have anything against the ideas mentioned, they're all good, but my preference is still to have the most recent team photo on the front page to keep things simple, and store previous team photos in a dedicated page.

**Comment by jayenashar** [comment]
> i think it's ok to show multiple teams on the home page

i don't know what i was smoking when i typed this.  i meant the one photo that has multiple teams in it, which is on the home page before this PR.  i have no objection to a separate page with multiple photos.

**Comment by ijnek** [comment]
@jayenashar Did you want me to change something, or are you fine as is?

image

This is the current photo on the main page. When you say the one photo that has multiple teams in it, do you mean that image?

I think its important to have a photo of the members that are current core developers on the team. Do you have another photo that you are part of? If not, I think the 2022 photo captures the majority of the current team.

**Comment by jayenashar** [comment]
> Did you want me to change something, or are you fine as is?

my preference is to keep the home page unchanged.

> This is the current photo on the main page. When you say the one photo that has multiple teams in it, do you mean that image?

yes, right.

> I think its important to have a photo of the members that are current core developers on the team. Do you have another photo that you are part of? If not, I think the 2022 photo captures the majority of the current team.

i'm not a current core developer.  i think it's important to have the photo but i don't think the main page's photo should change every year.  i can dig up some team photos for 2008, 2009, 2010, 2011, 2019 if you want to add them to the photos page.  maybe also good to caption the photos with each team members name, so we can mention members which are not shown.

**Comment by ijnek** [comment]
Ok, I think we've got different preferences. I think the front page should get updated at least once a year with the most recent members and I'm going to leave this PR that way. Current members - feel free to close this pull request if you decide not to proceed with this change.

>  i can dig up some team photos for 2008, 2009, 2010, 2011, 2019 if you want to add them to the photos page. maybe also good to caption the photos with each team members name, so we can mention members which are not shown.

Good ideas, but I'm not willing to take on that task.

**Review by jayenashar — CHANGES_REQUESTED** [review]
photos should be jpeg or webp (lossy compression) not png (lossless compression)

**Pull request merged**
